### PR TITLE
docs: added disableUpload and disableDownload to dev sync docs

### PR DESCRIPTION
**Pull request by gbates101**
**What issue type does this pull request address?** (keep at least one, remove the others)  
/kind documentation

**What is this pull request for? Which issues does it resolve?**
Documents supported workaround for #1004

### CODE REVIEW

**Comment by gbates101** [comment]
@FabianKramm Should I also place this in the versioned_docs for 4.5?

**Comment by LukasGentele** [comment]
@gbates101 thanks for the PR. This is really helpful. Would be great if you could add the new sections to v4.5 as well, yes. You can verify that these config options were part of v4.5 by checking the latest config version at this release tag: https://github.com/devspace-cloud/devspace/blob/v4.5.4/pkg/devspace/config/versions/latest/schema.go

**Comment by gbates101** [comment]
@LukasGentele Ah, good to know. I'll add it in 4.5 docs as well.

**Comment by LukasGentele** [comment]
Thanks, @gbates101!

**Pull request merged**
